name: SPARQL Queries Release

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::arrow
            any::jsonlite

      - name: Run SPARQL script
        run: Rscript R/nightly.R

      - name: Zip datasets folder
        run: |
          cd datasets
          zip -r ../datasets.zip .
        # This creates datasets.zip at the repository root, containing all files from the datasets folder

      - name: Create or update nightly release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Dataset
          files: datasets.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
