name: SPARQL Queries Nightly
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::tidyverse
            any::arrow
            any::jsonlite
      - name: Run SPARQL script
        run: Rscript R/nightly.R

      # Archive all output files (customize this pattern if needed)
      - name: Archive results
        run: |
          mkdir -p nightly_output
          cp -r datasets/* nightly_output/ 2>/dev/null || true

      - name: Create Release Tag
        id: tag
        run: |
          DATE=$(date +'%Y-%m-%d')
          TAG="nightly-dataset-${DATE}"
          echo "tag_name=${TAG}" >> $GITHUB_OUTPUT
          echo "release_name=Nightly Dataset - ${DATE}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: ${{ steps.tag.outputs.release_name }}
          body: "Automated nightly data files generated by workflow."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Results to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          files: nightly_output/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag latest release as 🍿
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "🍿";
            const sha = process.env.GITHUB_SHA;
            // Delete tag if exists
            try {
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
            } catch (e) {
              // Ignore if tag does not exist
            }
            // Create the tag at the current commit
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: sha
            });
            // Create or update the release with the tag 🍿
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const release = releases.data.find(r => r.tag_name === tag);
            if (release) {
              await github.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id,
                tag_name: tag,
                name: "🍿 Release",
                draft: false,
                prerelease: false
              });
            } else {
              await github.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag,
                name: "🍿 Release",
                draft: false,
                prerelease: false
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 3
